/*
 * trace-cruncher
 *
 * This is the trace-cruncher API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v1/",
		Index,
	},

	Route{
		"SystemCallDelete",
		strings.ToUpper("Delete"),
		"/v1/system_call",
		SystemCallDelete,
	},

	Route{
		"SystemCallGet",
		strings.ToUpper("Get"),
		"/v1/system_call",
		SystemCallGet,
	},

	Route{
		"SystemCallPost",
		strings.ToUpper("Post"),
		"/v1/system_call",
		SystemCallPost,
	},

	Route{
		"SystemCallPut",
		strings.ToUpper("Put"),
		"/v1/system_call",
		SystemCallPut,
	},
}
