apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../secret

generatorOptions:
 disableNameSuffixHash: true

secretGenerator:
- name: container-tracer-api-tls
  namespace: contrace
  files:
    - tls.crt=/path/to/your/tls.cert
    - tls.key=/path/to/your/tls.key
  type: "kubernetes.io/tls"
