apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-tracer-api
spec:
  template:
    spec:
      volumes:
      - name: tls
        secret:
          defaultMode: 420
          secretName: container-tracer-api-tls
      containers:
      - name: container-tracer
        volumeMounts:
        - name: tls
          mountPath: /tmp/api-tls
          readOnly: true
        env:
        - name: TRACE_KUBE_TLS_KEY
          value: "/tmp/api-tls/tls.key"
        - name: TRACE_KUBE_TLS_CERT
          value: "/tmp/api-tls/tls.crt"

            

