apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- container-tracer.yaml

images:
- name: vmware-labs/container-tracer/tracer-svc
  newName: vmware-labs/container-tracer/tracer-svc
  newTag: latest
- name: vmware-labs/container-tracer/tracer-node
  newName: vmware-labs/container-tracer/tracer-node
  newTag: latest